ports:
- port: 8050
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
tasks:
- init: /workspace/vpython_jupyter_notebook_gitpod/run.sh
  command: cp -r /workspace/vpython_jupyter_notebook_gitpod/.jupyter /home/gitpod/
